services:
  db:
    image: postgres:15
    container_name: manutencao_db
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  

  web:
    build: .
    container_name: manutencao_web
    restart: always
  
    volumes:
      - media_data:/app/media
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
              gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 5 --threads 3 --worker-class gthread --max-requests 50 --max-requests-jitter 10    ports:
      - "8080:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG}
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    restart: always

  celery_worker:
    build: .
    pull_policy: never
    command: celery -A config worker -l info
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG}
    depends_on:
      - redis
      - db
    restart: always

  celery_beat:
    build: .
    pull_policy: never
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG}
    depends_on:
      - redis
      - db
    restart: always

  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: manutencao-nginx
    restart: always
    ports:
      - '8085:80'  # Mudamos aqui! O mundo acessa pela 8085, o Nginx recebe internamente na 80
      - '81:81'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - web

volumes:
  postgres_data:
  media_data: # Criado para salvar as fotos dos chamados