# Generated by Django 6.0.1 on 2026-02-27 13:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import manutencao.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número do Poste/Padrão')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('solicitante', 'Solicitante'), ('mecanico', 'Mecânico'), ('mecanico_admin', 'Mecânico Admin')], max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Equipamento')),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, max_length=500, null=True, upload_to=manutencao.models.caminho_imagem_equipamento, validators=[manutencao.models.validar_tamanho_imagem])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('energia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manutencao.energia', verbose_name='Poste/Energia')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('equipamento', 'Equipamento'), ('avulso', 'Avulso')], max_length=20)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_progresso', 'Em Progresso'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('prioridade', models.IntegerField(choices=[(1, 'Alta'), (2, 'Média'), (3, 'Baixa')], default=3)),
                ('producao_parada', models.BooleanField(default=False, verbose_name='Produção Parada?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes_mecanico', models.TextField(blank=True)),
                ('mecanicos', models.ManyToManyField(blank=True, related_name='chamados_atribuidos', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados_criados', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manutencao.equipamento')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='chamados/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='manutencao.chamado')),
            ],
            options={
                'verbose_name': 'Imagem do Chamado',
                'verbose_name_plural': 'Imagens dos Chamados',
                'ordering': ['enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('energia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencao.energia', verbose_name='Poste/Energia')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='equipamento',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='manutencao.setor'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='setor_avulso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manutencao.setor'),
        ),
    ]