# Generated by Django 6.0.1 on 2026-01-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='maquina',
        ),
        migrations.AlterField(
            model_name='chamado',
            name='tipo',
            field=models.CharField(choices=[('equipamento', 'Equipamento'), ('avulso', 'Avulso')], max_length=20),
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='equipamentos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='manutencao.setor')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='chamado',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manutencao.equipamento'),
        ),
        migrations.CreateModel(
            name='ImagemChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='chamados/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='manutencao.chamado')),
            ],
            options={
                'verbose_name': 'Imagem do Chamado',
                'verbose_name_plural': 'Imagens dos Chamados',
                'ordering': ['enviado_em'],
            },
        ),
        migrations.DeleteModel(
            name='Maquina',
        ),
    ]
