# Generated by Django 6.0.1 on 2026-02-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código do Equipamento'),
        ),
    ]
