# Generated by Django 6.0.1 on 2026-01-26 18:10

import manutencao.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_remove_chamado_maquina_alter_chamado_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='mecanicos',
            field=models.ManyToManyField(blank=True, related_name='chamados_atribuidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='imagem',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=manutencao.models.caminho_imagem_equipamento, validators=[manutencao.models.validar_tamanho_imagem]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('solicitante', 'Solicitante'), ('mecanico', 'Mecânico'), ('mecanico_admin', 'Mecânico Admin')], max_length=20),
        ),
    ]
