# Generated by Django 6.0.1 on 2026-03-12 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_alter_equipamento_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='concluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_concluidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
