# Generated by Django 6.0.1 on 2026-03-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0003_chamado_concluido_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('solicitante', 'Solicitante'), ('mecanico', 'Mecânico'), ('mecanico_admin', 'Mecânico Admin'), ('solicitante_admin', 'Solicitante Admin')], max_length=20),
        ),
    ]
