# Generated by Django 6.0.1 on 2026-05-08 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0004_alter_usuario_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotinaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('equipamento', 'Equipamento'), ('setor', 'Setor (Manutenção Avulsa)')], default='equipamento', max_length=20)),
                ('nome_rotina', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('prioridade', models.IntegerField(default=2)),
                ('frequencia', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('personalizado', 'Personalizado (Dias)')], max_length=20)),
                ('intervalo_dias', models.PositiveIntegerField(blank=True, help_text='Usado se for personalizado', null=True)),
                ('ultima_execucao', models.DateField(auto_now_add=True)),
                ('proxima_execucao', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manutencao.equipamento')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manutencao.setor')),
            ],
        ),
    ]
