# Generated by Django 6.0.1 on 2026-05-20 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0005_rotinamanutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='is_rotina',
            field=models.BooleanField(default=False, verbose_name='Gerado por Rotina?'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='rotina_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manutencao.rotinamanutencao', verbose_name='Rotina de Origem'),
        ),
    ]
