# Generated by Django 6.0.1 on 2026-05-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0006_chamado_is_rotina_chamado_rotina_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotinamanutencao',
            name='ultima_execucao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
